// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: game_service.proto

package com.vou.common.proto.game;

public interface CreateGameResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:game.CreateGameResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * ID of the newly created EventGames record
   * </pre>
   *
   * <code>int64 event_game_id = 1;</code>
   * @return The eventGameId.
   */
  long getEventGameId();
}
