// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: game_service.proto

package com.vou.common.proto.game;

/**
 * Protobuf type {@code game.CreateGameRequest}
 */
public final class CreateGameRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:game.CreateGameRequest)
    CreateGameRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use CreateGameRequest.newBuilder() to construct.
  private CreateGameRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private CreateGameRequest() {
    gameName_ = "";
    gameType_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new CreateGameRequest();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private CreateGameRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            eventId_ = input.readInt64();
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            gameName_ = s;
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            gameType_ = s;
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.vou.common.proto.game.GameReceiver.internal_static_game_CreateGameRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.vou.common.proto.game.GameReceiver.internal_static_game_CreateGameRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.vou.common.proto.game.CreateGameRequest.class, com.vou.common.proto.game.CreateGameRequest.Builder.class);
  }

  public static final int EVENT_ID_FIELD_NUMBER = 1;
  private long eventId_;
  /**
   * <pre>
   * Event ID sent from event_service
   * </pre>
   *
   * <code>int64 event_id = 1;</code>
   *
   * @return The eventId.
   */
  @java.lang.Override
  public Long getEventId() {
    return eventId_;
  }

  public static final int GAME_NAME_FIELD_NUMBER = 2;
  private volatile java.lang.Object gameName_;
  /**
   * <pre>
   * Name of the game to create
   * </pre>
   *
   * <code>string game_name = 2;</code>
   * @return The gameName.
   */
  @java.lang.Override
  public java.lang.String getGameName() {
    java.lang.Object ref = gameName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      gameName_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Name of the game to create
   * </pre>
   *
   * <code>string game_name = 2;</code>
   * @return The bytes for gameName.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getGameNameBytes() {
    java.lang.Object ref = gameName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      gameName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int GAME_TYPE_FIELD_NUMBER = 3;
  private volatile java.lang.Object gameType_;
  /**
   * <pre>
   * Type of the game
   * </pre>
   *
   * <code>string game_type = 3;</code>
   * @return The gameType.
   */
  @java.lang.Override
  public java.lang.String getGameType() {
    java.lang.Object ref = gameType_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      gameType_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Type of the game
   * </pre>
   *
   * <code>string game_type = 3;</code>
   * @return The bytes for gameType.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getGameTypeBytes() {
    java.lang.Object ref = gameType_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      gameType_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (eventId_ != 0L) {
      output.writeInt64(1, eventId_);
    }
    if (!getGameNameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, gameName_);
    }
    if (!getGameTypeBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, gameType_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (eventId_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(1, eventId_);
    }
    if (!getGameNameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, gameName_);
    }
    if (!getGameTypeBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, gameType_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.vou.common.proto.game.CreateGameRequest)) {
      return super.equals(obj);
    }
    com.vou.common.proto.game.CreateGameRequest other = (com.vou.common.proto.game.CreateGameRequest) obj;

    if (getEventId()
        != other.getEventId()) return false;
    if (!getGameName()
        .equals(other.getGameName())) return false;
    if (!getGameType()
        .equals(other.getGameType())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + EVENT_ID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getEventId());
    hash = (37 * hash) + GAME_NAME_FIELD_NUMBER;
    hash = (53 * hash) + getGameName().hashCode();
    hash = (37 * hash) + GAME_TYPE_FIELD_NUMBER;
    hash = (53 * hash) + getGameType().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.vou.common.proto.game.CreateGameRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.vou.common.proto.game.CreateGameRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.vou.common.proto.game.CreateGameRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.vou.common.proto.game.CreateGameRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.vou.common.proto.game.CreateGameRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.vou.common.proto.game.CreateGameRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.vou.common.proto.game.CreateGameRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.vou.common.proto.game.CreateGameRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.vou.common.proto.game.CreateGameRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.vou.common.proto.game.CreateGameRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.vou.common.proto.game.CreateGameRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.vou.common.proto.game.CreateGameRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.vou.common.proto.game.CreateGameRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code game.CreateGameRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:game.CreateGameRequest)
      com.vou.common.proto.game.CreateGameRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.vou.common.proto.game.GameReceiver.internal_static_game_CreateGameRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.vou.common.proto.game.GameReceiver.internal_static_game_CreateGameRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.vou.common.proto.game.CreateGameRequest.class, com.vou.common.proto.game.CreateGameRequest.Builder.class);
    }

    // Construct using com.vou.common.proto.game.CreateGameRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      eventId_ = 0L;

      gameName_ = "";

      gameType_ = "";

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.vou.common.proto.game.GameReceiver.internal_static_game_CreateGameRequest_descriptor;
    }

    @java.lang.Override
    public com.vou.common.proto.game.CreateGameRequest getDefaultInstanceForType() {
      return com.vou.common.proto.game.CreateGameRequest.getDefaultInstance();
    }

    @java.lang.Override
    public com.vou.common.proto.game.CreateGameRequest build() {
      com.vou.common.proto.game.CreateGameRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.vou.common.proto.game.CreateGameRequest buildPartial() {
      com.vou.common.proto.game.CreateGameRequest result = new com.vou.common.proto.game.CreateGameRequest(this);
      result.eventId_ = eventId_;
      result.gameName_ = gameName_;
      result.gameType_ = gameType_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.vou.common.proto.game.CreateGameRequest) {
        return mergeFrom((com.vou.common.proto.game.CreateGameRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.vou.common.proto.game.CreateGameRequest other) {
      if (other == com.vou.common.proto.game.CreateGameRequest.getDefaultInstance()) return this;
      if (other.getEventId() != 0L) {
        setEventId(other.getEventId());
      }
      if (!other.getGameName().isEmpty()) {
        gameName_ = other.gameName_;
        onChanged();
      }
      if (!other.getGameType().isEmpty()) {
        gameType_ = other.gameType_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.vou.common.proto.game.CreateGameRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.vou.common.proto.game.CreateGameRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private long eventId_ ;
    /**
     * <pre>
     * Event ID sent from event_service
     * </pre>
     *
     * <code>int64 event_id = 1;</code>
     *
     * @return The eventId.
     */
    @java.lang.Override
    public Long getEventId() {
      return eventId_;
    }
    /**
     * <pre>
     * Event ID sent from event_service
     * </pre>
     *
     * <code>int64 event_id = 1;</code>
     * @param value The eventId to set.
     * @return This builder for chaining.
     */
    public Builder setEventId(long value) {
      
      eventId_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Event ID sent from event_service
     * </pre>
     *
     * <code>int64 event_id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearEventId() {
      
      eventId_ = 0L;
      onChanged();
      return this;
    }

    private java.lang.Object gameName_ = "";
    /**
     * <pre>
     * Name of the game to create
     * </pre>
     *
     * <code>string game_name = 2;</code>
     * @return The gameName.
     */
    public java.lang.String getGameName() {
      java.lang.Object ref = gameName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        gameName_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * Name of the game to create
     * </pre>
     *
     * <code>string game_name = 2;</code>
     * @return The bytes for gameName.
     */
    public com.google.protobuf.ByteString
        getGameNameBytes() {
      java.lang.Object ref = gameName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        gameName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Name of the game to create
     * </pre>
     *
     * <code>string game_name = 2;</code>
     * @param value The gameName to set.
     * @return This builder for chaining.
     */
    public Builder setGameName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      gameName_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Name of the game to create
     * </pre>
     *
     * <code>string game_name = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearGameName() {
      
      gameName_ = getDefaultInstance().getGameName();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Name of the game to create
     * </pre>
     *
     * <code>string game_name = 2;</code>
     * @param value The bytes for gameName to set.
     * @return This builder for chaining.
     */
    public Builder setGameNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      gameName_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object gameType_ = "";
    /**
     * <pre>
     * Type of the game
     * </pre>
     *
     * <code>string game_type = 3;</code>
     * @return The gameType.
     */
    public java.lang.String getGameType() {
      java.lang.Object ref = gameType_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        gameType_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * Type of the game
     * </pre>
     *
     * <code>string game_type = 3;</code>
     * @return The bytes for gameType.
     */
    public com.google.protobuf.ByteString
        getGameTypeBytes() {
      java.lang.Object ref = gameType_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        gameType_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Type of the game
     * </pre>
     *
     * <code>string game_type = 3;</code>
     * @param value The gameType to set.
     * @return This builder for chaining.
     */
    public Builder setGameType(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      gameType_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Type of the game
     * </pre>
     *
     * <code>string game_type = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearGameType() {
      
      gameType_ = getDefaultInstance().getGameType();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Type of the game
     * </pre>
     *
     * <code>string game_type = 3;</code>
     * @param value The bytes for gameType to set.
     * @return This builder for chaining.
     */
    public Builder setGameTypeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      gameType_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:game.CreateGameRequest)
  }

  // @@protoc_insertion_point(class_scope:game.CreateGameRequest)
  private static final com.vou.common.proto.game.CreateGameRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.vou.common.proto.game.CreateGameRequest();
  }

  public static com.vou.common.proto.game.CreateGameRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<CreateGameRequest>
      PARSER = new com.google.protobuf.AbstractParser<CreateGameRequest>() {
    @java.lang.Override
    public CreateGameRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new CreateGameRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<CreateGameRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<CreateGameRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.vou.common.proto.game.CreateGameRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

