// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: game_service.proto

package com.vou.common.proto.game;

public interface CreateGameRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:game.CreateGameRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Event ID sent from event_service
   * </pre>
   *
   * <code>int64 event_id = 1;</code>
   * @return The eventId.
   */
  long getEventId();

  /**
   * <pre>
   * Name of the game to create
   * </pre>
   *
   * <code>string game_name = 2;</code>
   * @return The gameName.
   */
  java.lang.String getGameName();
  /**
   * <pre>
   * Name of the game to create
   * </pre>
   *
   * <code>string game_name = 2;</code>
   * @return The bytes for gameName.
   */
  com.google.protobuf.ByteString
      getGameNameBytes();

  /**
   * <pre>
   * Type of the game
   * </pre>
   *
   * <code>string game_type = 3;</code>
   * @return The gameType.
   */
  java.lang.String getGameType();
  /**
   * <pre>
   * Type of the game
   * </pre>
   *
   * <code>string game_type = 3;</code>
   * @return The bytes for gameType.
   */
  com.google.protobuf.ByteString
      getGameTypeBytes();
}
