// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/auth_service.proto

package com.vou.common.proto;

public interface AuthTokenMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:auth.AuthTokenMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string token = 1;</code>
   * @return The token.
   */
  java.lang.String getToken();
  /**
   * <code>string token = 1;</code>
   * @return The bytes for token.
   */
  com.google.protobuf.ByteString
      getTokenBytes();
}
