// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/auth_service.proto

package com.vou.common.proto;

public interface AuthTokenResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:auth.AuthTokenResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string message = 1;</code>
   * @return The message.
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 1;</code>
   * @return The bytes for message.
   */
  com.google.protobuf.ByteString
      getMessageBytes();
}
