// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/event_service.proto

package com.vou.common.proto;

public final class EventServiceProto {
  private EventServiceProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_event_RequestUser_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_event_RequestUser_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_event_ResponseBrand_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_event_ResponseBrand_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_event_Point_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_event_Point_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\031proto/event_service.proto\022\005event\"\035\n\013Re" +
      "questUser\022\016\n\006userId\030\001 \001(\t\"v\n\rResponseBra" +
      "nd\022\n\n\002id\030\001 \001(\014\022\014\n\004name\030\002 \001(\t\022\r\n\005phone\030\003 " +
      "\001(\t\022\r\n\005field\030\004 \001(\t\022\035\n\007address\030\005 \001(\0132\014.ev" +
      "ent.Point\022\016\n\006status\030\006 \001(\t\"\035\n\005Point\022\t\n\001x\030" +
      "\001 \001(\001\022\t\n\001y\030\002 \001(\0012G\n\017GetBrandService\0224\n\010g" +
      "etBrand\022\022.event.RequestUser\032\024.event.Resp" +
      "onseBrandB+\n\024com.vou.common.protoB\021Event" +
      "ServiceProtoP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_event_RequestUser_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_event_RequestUser_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_event_RequestUser_descriptor,
        new java.lang.String[] { "UserId", });
    internal_static_event_ResponseBrand_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_event_ResponseBrand_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_event_ResponseBrand_descriptor,
        new java.lang.String[] { "Id", "Name", "Phone", "Field", "Address", "Status", });
    internal_static_event_Point_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_event_Point_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_event_Point_descriptor,
        new java.lang.String[] { "X", "Y", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
