// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/event_service.proto

package com.vou.common.proto;

public interface PointOrBuilder extends
    // @@protoc_insertion_point(interface_extends:event.Point)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Tọa độ X (kinh độ)
   * </pre>
   *
   * <code>double x = 1;</code>
   * @return The x.
   */
  double getX();

  /**
   * <pre>
   * Tọa độ Y (vĩ độ)
   * </pre>
   *
   * <code>double y = 2;</code>
   * @return The y.
   */
  double getY();
}
