// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/event_service.proto

package com.vou.common.proto;

public interface ResponseBrandOrBuilder extends
    // @@protoc_insertion_point(interface_extends:event.ResponseBrand)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * ID dạng binary (UUID)
   * </pre>
   *
   * <code>bytes id = 1;</code>
   * @return The id.
   */
  com.google.protobuf.ByteString getId();

  /**
   * <pre>
   * Tên thương hiệu
   * </pre>
   *
   * <code>string name = 2;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <pre>
   * Tên thương hiệu
   * </pre>
   *
   * <code>string name = 2;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <pre>
   * Số điện thoại
   * </pre>
   *
   * <code>string phone = 3;</code>
   * @return The phone.
   */
  java.lang.String getPhone();
  /**
   * <pre>
   * Số điện thoại
   * </pre>
   *
   * <code>string phone = 3;</code>
   * @return The bytes for phone.
   */
  com.google.protobuf.ByteString
      getPhoneBytes();

  /**
   * <pre>
   * Lĩnh vực hoạt động
   * </pre>
   *
   * <code>string field = 4;</code>
   * @return The field.
   */
  java.lang.String getField();
  /**
   * <pre>
   * Lĩnh vực hoạt động
   * </pre>
   *
   * <code>string field = 4;</code>
   * @return The bytes for field.
   */
  com.google.protobuf.ByteString
      getFieldBytes();

  /**
   * <pre>
   * Địa chỉ (dạng tọa độ)
   * </pre>
   *
   * <code>.event.Point address = 5;</code>
   * @return Whether the address field is set.
   */
  boolean hasAddress();
  /**
   * <pre>
   * Địa chỉ (dạng tọa độ)
   * </pre>
   *
   * <code>.event.Point address = 5;</code>
   * @return The address.
   */
  com.vou.common.proto.Point getAddress();
  /**
   * <pre>
   * Địa chỉ (dạng tọa độ)
   * </pre>
   *
   * <code>.event.Point address = 5;</code>
   */
  com.vou.common.proto.PointOrBuilder getAddressOrBuilder();

  /**
   * <pre>
   * Trạng thái ('active' hoặc 'inactive')
   * </pre>
   *
   * <code>string status = 6;</code>
   * @return The status.
   */
  java.lang.String getStatus();
  /**
   * <pre>
   * Trạng thái ('active' hoặc 'inactive')
   * </pre>
   *
   * <code>string status = 6;</code>
   * @return The bytes for status.
   */
  com.google.protobuf.ByteString
      getStatusBytes();
}
