// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/auth_service.proto

package com.vou.common.proto;

public interface UserInfoMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:auth.UserInfoMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string userId = 1;</code>
   * @return The userId.
   */
  java.lang.String getUserId();
  /**
   * <code>string userId = 1;</code>
   * @return The bytes for userId.
   */
  com.google.protobuf.ByteString
      getUserIdBytes();

  /**
   * <code>string userRole = 2;</code>
   * @return The userRole.
   */
  java.lang.String getUserRole();
  /**
   * <code>string userRole = 2;</code>
   * @return The bytes for userRole.
   */
  com.google.protobuf.ByteString
      getUserRoleBytes();
}
