// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/user_service.proto

package com.vou.common.proto;

public final class UserServiceProto {
  private UserServiceProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_user_RequestAuth_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_user_RequestAuth_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_user_ResponseAuth_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_user_ResponseAuth_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\030proto/user_service.proto\022\004user\"\035\n\013Requ" +
      "estAuth\022\016\n\006userId\030\001 \001(\t\"]\n\014ResponseAuth\022" +
      "\016\n\006userId\030\001 \001(\t\022\020\n\010username\030\002 \001(\t\022\r\n\005ema" +
      "il\030\003 \001(\t\022\014\n\004role\030\004 \001(\t\022\016\n\006status\030\005 \001(\t2?" +
      "\n\013UserService\0220\n\007getAuth\022\021.user.RequestA" +
      "uth\032\022.user.ResponseAuthB*\n\024com.vou.commo" +
      "n.protoB\020UserServiceProtoP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_user_RequestAuth_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_user_RequestAuth_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_user_RequestAuth_descriptor,
        new java.lang.String[] { "UserId", });
    internal_static_user_ResponseAuth_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_user_ResponseAuth_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_user_ResponseAuth_descriptor,
        new java.lang.String[] { "UserId", "Username", "Email", "Role", "Status", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
