// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/event_service.proto

package com.vou.common.proto.event;

public final class EventReceiver {
  private EventReceiver() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_event_GetVoucherMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_event_GetVoucherMessage_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_event_GetVoucherResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_event_GetVoucherResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\031proto/event_service.proto\022\005event\"&\n\021Ge" +
      "tVoucherMessage\022\021\n\tvoucherId\030\001 \001(\t\"\237\001\n\022G" +
      "etVoucherResponse\022\021\n\tvoucherId\030\001 \001(\t\022\017\n\007" +
      "eventId\030\002 \001(\t\022\014\n\004code\030\003 \001(\t\022\016\n\006qrCode\030\004 " +
      "\001(\t\022\r\n\005value\030\005 \001(\001\022\023\n\013description\030\006 \001(\t\022" +
      "\023\n\013expiredDate\030\007 \001(\t\022\016\n\006status\030\010 \001(\t2U\n\014" +
      "EventService\022E\n\016getVoucherInfo\022\030.event.G" +
      "etVoucherMessage\032\031.event.GetVoucherRespo" +
      "nseB-\n\032com.vou.common.proto.eventB\rEvent" +
      "ReceiverP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_event_GetVoucherMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_event_GetVoucherMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_event_GetVoucherMessage_descriptor,
        new java.lang.String[] { "VoucherId", });
    internal_static_event_GetVoucherResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_event_GetVoucherResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_event_GetVoucherResponse_descriptor,
        new java.lang.String[] { "VoucherId", "EventId", "Code", "QrCode", "Value", "Description", "ExpiredDate", "Status", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
