// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/event_service.proto

package com.vou.common.proto.event;

public interface GetVoucherMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:event.GetVoucherMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string voucherId = 1;</code>
   * @return The voucherId.
   */
  java.lang.String getVoucherId();
  /**
   * <code>string voucherId = 1;</code>
   * @return The bytes for voucherId.
   */
  com.google.protobuf.ByteString
      getVoucherIdBytes();
}
