// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/event_service.proto

package com.vou.common.proto.event;

public interface GetVoucherResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:event.GetVoucherResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string voucherId = 1;</code>
   * @return The voucherId.
   */
  java.lang.String getVoucherId();
  /**
   * <code>string voucherId = 1;</code>
   * @return The bytes for voucherId.
   */
  com.google.protobuf.ByteString
      getVoucherIdBytes();

  /**
   * <code>string eventId = 2;</code>
   * @return The eventId.
   */
  java.lang.String getEventId();
  /**
   * <code>string eventId = 2;</code>
   * @return The bytes for eventId.
   */
  com.google.protobuf.ByteString
      getEventIdBytes();

  /**
   * <code>string code = 3;</code>
   * @return The code.
   */
  java.lang.String getCode();
  /**
   * <code>string code = 3;</code>
   * @return The bytes for code.
   */
  com.google.protobuf.ByteString
      getCodeBytes();

  /**
   * <code>string qrCode = 4;</code>
   * @return The qrCode.
   */
  java.lang.String getQrCode();
  /**
   * <code>string qrCode = 4;</code>
   * @return The bytes for qrCode.
   */
  com.google.protobuf.ByteString
      getQrCodeBytes();

  /**
   * <code>double value = 5;</code>
   * @return The value.
   */
  double getValue();

  /**
   * <code>string description = 6;</code>
   * @return The description.
   */
  java.lang.String getDescription();
  /**
   * <code>string description = 6;</code>
   * @return The bytes for description.
   */
  com.google.protobuf.ByteString
      getDescriptionBytes();

  /**
   * <code>string expiredDate = 7;</code>
   * @return The expiredDate.
   */
  java.lang.String getExpiredDate();
  /**
   * <code>string expiredDate = 7;</code>
   * @return The bytes for expiredDate.
   */
  com.google.protobuf.ByteString
      getExpiredDateBytes();

  /**
   * <code>string status = 8;</code>
   * @return The status.
   */
  java.lang.String getStatus();
  /**
   * <code>string status = 8;</code>
   * @return The bytes for status.
   */
  com.google.protobuf.ByteString
      getStatusBytes();
}
