server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-service:8761/eureka/
  instance:
    preferIpAddress: true

jwt:
  secret: U2FGaW5hbFByb2plY3RfU2FGaW5hbFByb2plY3RfU2FGaW5hbFByb2plY3RfU2FGaW5hbFByb2plY3Q=