// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/auth_service.proto

package com.vou.common.proto.auth;

public final class AuthReceiver {
  private AuthReceiver() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_auth_RequestInfoMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_auth_RequestInfoMessage_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_auth_RequestInfoResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_auth_RequestInfoResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\030proto/auth_service.proto\022\004auth\"$\n\022Requ" +
      "estInfoMessage\022\016\n\006userId\030\001 \001(\t\"d\n\023Reques" +
      "tInfoResponse\022\016\n\006userId\030\001 \001(\t\022\r\n\005email\030\002" +
      " \001(\t\022\020\n\010username\030\003 \001(\t\022\016\n\006status\030\004 \001(\t\022\014" +
      "\n\004role\030\005 \001(\t2M\n\013AuthService\022>\n\007getInfo\022\030" +
      ".auth.RequestInfoMessage\032\031.auth.RequestI" +
      "nfoResponseB+\n\031com.vou.common.proto.auth" +
      "B\014AuthReceiverP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_auth_RequestInfoMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_auth_RequestInfoMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_auth_RequestInfoMessage_descriptor,
        new java.lang.String[] { "UserId", });
    internal_static_auth_RequestInfoResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_auth_RequestInfoResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_auth_RequestInfoResponse_descriptor,
        new java.lang.String[] { "UserId", "Email", "Username", "Status", "Role", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
