// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/user_service.proto

package com.vou.common.proto.user;

public final class UserReceiver {
  private UserReceiver() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_user_SendUIDMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_user_SendUIDMessage_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_user_SendUIDResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_user_SendUIDResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_user_GetUserIdFromEmailMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_user_GetUserIdFromEmailMessage_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_user_GetUserIdFromEmailResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_user_GetUserIdFromEmailResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_user_CurrentUIDMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_user_CurrentUIDMessage_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_user_CurrentUIDResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_user_CurrentUIDResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\030proto/user_service.proto\022\004user\"=\n\016Send" +
      "UIDMessage\022\016\n\006userId\030\001 \001(\t\022\014\n\004role\030\002 \001(\t" +
      "\022\r\n\005email\030\003 \001(\t\"\"\n\017SendUIDResponse\022\017\n\007me" +
      "ssage\030\001 \001(\t\"*\n\031GetUserIdFromEmailMessage" +
      "\022\r\n\005email\030\001 \001(\t\",\n\032GetUserIdFromEmailRes" +
      "ponse\022\016\n\006userId\030\001 \001(\t\"$\n\021CurrentUIDMessa" +
      "ge\022\017\n\007message\030\001 \001(\t\"$\n\022CurrentUIDRespons" +
      "e\022\016\n\006userId\030\001 \001(\t2\350\001\n\013UserService\0229\n\nrec" +
      "eiveUID\022\024.user.SendUIDMessage\032\025.user.Sen" +
      "dUIDResponse\022W\n\022getUserIdFromEmail\022\037.use" +
      "r.GetUserIdFromEmailMessage\032 .user.GetUs" +
      "erIdFromEmailResponse\022E\n\020getCurrentUserI" +
      "d\022\027.user.CurrentUIDMessage\032\030.user.Curren" +
      "tUIDResponseB+\n\031com.vou.common.proto.use" +
      "rB\014UserReceiverP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_user_SendUIDMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_user_SendUIDMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_user_SendUIDMessage_descriptor,
        new java.lang.String[] { "UserId", "Role", "Email", });
    internal_static_user_SendUIDResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_user_SendUIDResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_user_SendUIDResponse_descriptor,
        new java.lang.String[] { "Message", });
    internal_static_user_GetUserIdFromEmailMessage_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_user_GetUserIdFromEmailMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_user_GetUserIdFromEmailMessage_descriptor,
        new java.lang.String[] { "Email", });
    internal_static_user_GetUserIdFromEmailResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_user_GetUserIdFromEmailResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_user_GetUserIdFromEmailResponse_descriptor,
        new java.lang.String[] { "UserId", });
    internal_static_user_CurrentUIDMessage_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_user_CurrentUIDMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_user_CurrentUIDMessage_descriptor,
        new java.lang.String[] { "Message", });
    internal_static_user_CurrentUIDResponse_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_user_CurrentUIDResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_user_CurrentUIDResponse_descriptor,
        new java.lang.String[] { "UserId", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
