// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/user_service.proto

package com.vou.common;

public interface EmptyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:user.Empty)
    com.google.protobuf.MessageOrBuilder {
}
